### ISSUE TITLE
should the generated quickstarts use parent poms at all?

### ISSUE THREAD

**Issue by jstrachan** [fabric8-launcher/launcher-planning#10] opened 2017-04-11 15:47 UTC
We went through this journey on fabric8 too; started with a monolith git repo; then had lots of git repos then realised that the easiest to use generated quickstart has no parent pom - as end users will almost certainly wanna add their own parent pom to do things like set the `<distribution>` stuff or whatever.

So removing a parent pom makes it easier for users to take whats generated and use it with whatever on premise parent poms that they may wanna use. The downside though is it makes it harder to write lots of independent quickstarts that you keep in sync in terms of versions and stuff. That led us to creating this CD Pipeline to keep our [fabric8-quickstarts](https://github.com/fabric8-quickstarts/) upstream projects in sync: https://github.com/fabric8io/fabric8-maven-dependencies/

I guess its up to your team to decide which way you wanna go on this one really. You could 

* just ignore me and close this issue ;)
* get the wizard to strip out the parent pom in the generated project (though that runs the risk that the lack of parent pom breaks the project - but so long as you have CI  / CD on the wizard output that should be fine) 
* remove the parent poms and yse something like this CI / CD process to keep things in sync https://github.com/fabric8io/fabric8-maven-dependencies/

its up to you to decide but personally I'd rather consume generated quickstarts with no parent `pom.xml`

**Comment by pmuir** [comment] 2017-04-11 16:06
Agreed. This was the approach we took for the JBoss Developer quickstarts. We build the quickstarts as a learning experience, and having a parent POM makes them harder to understand.

The generated approach is great as it removes the overhead for manually maintaining stuff.

**Comment by gastaldi** [comment] 2017-04-11 16:21
Not sure I agree that removing the parent pom is the best approach. Inlining would require quite some logic to get it right because ordering matter and it might get worse if a booster overrides one of the configuration. So -1 to that :)

**Comment by pmuir** [comment] 2017-04-11 16:25
@gastaldi yep, it's a tough one, but in the end we felt having a parent really damaged the user's experience as it meant the quickstart basically wasn't a good starting point for them anymore.

Is the parent POM that we're distributing here directly usable for an end user without modification? When would they need to untangle it - how far into their journey?

**Comment by gastaldi** [comment] 2017-04-11 16:28
@pmuir I think the best option would be having a BOM, but you can't assign plugin versions to that unfortunately. The parent pom just contains the common dependencies for all the boosters, and by design it should be kept simple

**Comment by pmuir** [comment] 2017-04-11 16:34
Yes, a BOM is the best approach, but like you say it won't work for plugins. If you can really keep it to common deps that are relevant to the quickstarts themselves included, then you may make it work, but as we already saw that rule got broken by including the nexus plugins (nothing to do with the quickstarts per se). 

Also need to be careful only to put truly common deps in.

**Comment by jstrachan** [comment] 2017-04-11 17:46
yeah - a BOM then using a CD pipeline to align versions of the BOM + mvn plugins sounds a nice simple solution really. (Such a shame you can't include mvn plugin versions in a BOM!)

Here's a project and Jenkinsfile you can reuse if you wanna go in that direction: https://github.com/fabric8io/fabric8-maven-dependencies/ we have CI / CD infrastructure we can run it on too - give us a shout if you wanna use it. Right now that automates the PRs against all our quickstarts whenever we change a dependency or plugin version

**Comment by cescoffier** [comment] 2017-04-12 06:10
The parent booster does not define much dependency versions, it's mainly about plugin versions.  It also configures the infamous Eclipse M2E plugin to get the import into Eclipse working. This should not be in the booster pom, and IMHO, this should not exist at all. 

BOM how they are implemented in Maven cannot handle plugin versions. Notice that bom comes with a set of drawbacks about ordering and scopes. 

The Nexus plugin issue was due to a usage of the `deploy` phase for something that is not a _deployment_ for Maven. I agree it's confusing, but deployment for Maven is not about running artifacts.

**Comment by cescoffier** [comment] 2017-04-12 06:11
If it would be a bom, it would contain a single dependency:

```
<dependency>
      <groupId>io.openshift</groupId>
      <artifactId>openshift-test-utils</artifactId>
      <version>${booster-common.version}</version>
</dependency>
```

**Comment by cescoffier** [comment] 2017-04-12 06:34
BTW the dependency listed above is a temporary dependency until we switch to Arquillian Cube. So, it would be an empty BOM...

**Comment by bartoszmajsak** [comment] 2018-01-19 18:13
@gastaldi was there any progress on this one?

**Comment by gastaldi** [comment] 2018-01-19 18:17
wdyt @cescoffier ?

**Comment by quintesse** [comment] 2018-01-19 18:26
Also +1 on this. if we want this to be a community project I can't imagine telling people they need to use a parent POM. If you create Booster projects that people are supposed to use as a basis for their own application then there shouldn't be any extra dependencies. And if the Booster is meant for educational purposes instead you also don't want to have to explain to people what that parent POM is for. I understand why it's easier _for us_, but in this case it's much more important what's easy for our _end users_.

**Comment by gastaldi** [comment] 2018-01-19 19:07
I am not entirely sure we'd want to get rid of a parent pom completely. Having a parent POM is a good practice and the majority of Maven applications out there has a parent pom. Nobody wants to redefine everything a new projects is created.

Perhaps we could ask for the parent pom coordinates in our wizard steps? That would be a much more realistic scenario IMHO.

**Comment by quintesse** [comment] 2018-01-19 21:04
I'm not sure how that would help? First it means that we would have to make our Boosters independent of the current parent pom anyway (= good), but then we'd add this unknown entity to the generated pom while there's no code that makes use of it anyway.

Now the moment the user starts adding code they might need it, but couldn't they just add that parent reference themselves? I'm not sure I see the added value of putting that in the UI (and on the other hand I see lots of possible problems with boosters not working because people added references to faulty parent poms).

**Comment by Ladicek** [comment] 2018-01-23 10:18
If there was a vote, I'd totally vote for removing any and all parent POMs from the boosters for the reasons stated above -- it damages the learning experience. With Spring Boot plans of introducing a _second_ parent POM, it's even worse. Of course removing parent POMs means much bigger maintenance cost for us.

**Comment by gastaldi** [comment] 2018-01-23 10:32
Right, I think that makes sense. 

Removing the poms would also make easier to introduce service composition in the future (without the need to calculate the effective POM) so +1 to remove.

**Comment by gastaldi** [comment] 2019-07-08 13:09
Starters are already refactored to not depend on the parent pom. Closing

**Closed by gastaldi** 2019-07-08 13:09 UTC
