### ISSUE TITLE
Remove the 'Select Target Environment' step when running in OpenShift

### ISSUE THREAD

**Issue by david-martin** [fabric8-launcher/launcher-planning#173] opened 2018-08-24 13:32 UTC
If I'm running Launcher on OpenShift e.g. in my own cluster, there will only ever be 1 option for the cluster I want to deploy to.
I won't need the option to download and build locally.
Therefore, the below step in the wizard should be possible to disable completely in this scenario.

![image](https://user-images.githubusercontent.com/878251/44587297-72f8ff80-a7aa-11e8-8260-59eec9069f42.png)

Related to #171

**Comment by Ladicek** [comment] 2018-08-24 13:36
> I won't need the option to download and build locally.

That's a bold statement.

**Comment by david-martin** [comment] 2018-08-24 14:06
> That's a bold statement

:smile: Indeed.

My thinking is why would you Build and Run locally when you can create stuff (BuildConfig, Deployment etc...) in an OpenShift cluster that you are already authorized against.

If running Launcher in OpenShift, the flow should take advantage of this and minimize the choices (at least intiially) and get them going.

**Comment by Ladicek** [comment] 2018-08-24 14:43
Because perhaps that single OpenShift cluster is something my company set up for everyone, and I just want to play locally with Minishift?

**Comment by david-martin** [comment] 2018-08-24 14:50
@Ladicek How about this.

What if there was an option to *not* show the 'Select your OpenShift cluster' selection if there is only 1 cluster that the user is already authorized to.
Having a choice of cluster doesn't make sense in this context where I only know of 1 cluster.

I'm trying to think of the experience from the point of view of a user coming to an OpenShift cluster that has a bunch of things already available on it, including Launcher, and what they would/wouldn't expect to see.

**Comment by gastaldi** [comment] 2018-08-24 15:26
Duplicate of https://github.com/fabric8-launcher/ngx-launcher/issues/353

**Comment by Ladicek** [comment] 2018-08-27 09:56
If I could access Launcher from the OpenShift web console, I'd like to select "deploy to this cluster". In all other cases, I probably want to know what cluster the Launcher targets, even though I don't have to select it.

**Comment by david-martin** [comment] 2018-08-27 10:57
> what cluster the Launcher targets

In my scenario this Launcher is tied to the cluster it is installed to.
It will not be used to deploy things to any other cluster.
Does that make sense?

**Comment by ALRubinger** [comment] 2018-09-13 18:35
@Ladicek I think I see what David is getting at here.  In this case it's Integreatly, an opinionated environment that comes with a set of more constrained "walkthroughs" guiding the experience.  "Download as ZIP" is not part of those stories, and he'd like a configurable way to omit that from the Launcher UI for the environments in which that makes sense.

@david-martin About right?

If so, my +1 to the concept and you 'n @gastaldi can work through when this needs to be done by.

**Comment by david-martin** [comment] 2018-09-14 08:11
@ALRubinger That summarizes it well. Thanks for helping clarify.

**Comment by ALRubinger** [comment] 2019-03-14 05:23
I believe this may be handled by #205

**Comment by ALRubinger** [comment] 2019-03-14 05:25
Note: newer versions of the launcher do not have target environment as a "step".  The option is available to users to either download or launch to a configured cluster.

**Comment by gastaldi** [comment] 2019-07-08 16:31
Closing as explained above

**Closed by gastaldi** 2019-07-08 16:31 UTC
