### ISSUE TITLE
the .zip file is always called booster.zip, but the Launcher UI tells me to "unzip <my booster name>.zip"

### ISSUE THREAD

**Issue by Ladicek** [fabric8-launcher/launcher-planning#168] opened 2018-06-25 14:03 UTC

**Comment by Ladicek** [comment] 2018-06-29 07:40
Looking at the documentation, what's probably wrong is the name of the .zip file; I believe it really is supposed to be called `<my booster name>.zip`.

**Comment by gastaldi** [comment] 2018-08-23 08:49
Duplicate of https://github.com/fabric8-launcher/launcher-frontend/issues/593

**Comment by ALRubinger** [comment] 2018-08-23 08:49
Let's name the ZIP file to be what is shown in the UI.

**Closed** 2018-08-30 17:55 UTC
